### ISSUE TITLE
What is function to get deposit address ?

### ISSUE THREAD

**Issue by ndphuong** [JKorf/CoinEx.Net#10]
Hi,

I want to get deposit address of coin?

Are you lack this function ?

**Comment by JKorf** [comment]
I've looked, but I can't find an endpoint to retrieve deposit addresses in the API. If you have any information about an endpoint like this please let me know.

**Comment by pcartwright81** [comment]
You could use the deposit history and just select the addresses.  I have added this endpoint in my pull request.

**Comment by JKorf** [comment]
The method suggested by @pcartwright81 is the only work around as far as I know
