### ISSUE TITLE
Creating Authorization code

### ISSUE THREAD

**Issue by pediotroni** [JKorf/CoinEx.Net#14]
Short Form of my issue:
*) My software keep receiving this error message when I want to retrieve my account balance:

First lets try if information of the provider itself is valid or not?
According to 
https://github.com/coinexcom/coinex_exchange_api/wiki/012security_authorization
we need a authorization code, which is an MD5 to sign in, let see the process.
1- Sort all parameter, As I have only one: tonce
2- Generate String to sign, which means add access_id at the beginning and secret_key at the end
so:
access_id=123&tonce=1590000000000&secret_key=12345
This shall go to an MD5 hashing process, assuming it would be AaBbCc
It has to be upper cased then this will go to header:
authorization:AABBCC

Note that in their sample "?" does not exists.
The BaseURL is: https://api.coinex.com/v1/
and the folder/directory path is: balance/info
Complete request to GET is:
https://api.coinex.com/v1/balance/info?access_id=123&tonce=1590000000000&secret_key=12345

But I receive error:
{"code":25,"data":{},"message":"Signature error."}

Now my confusion starts
maybe "?" shall be added, maybe complete URL shall be MD5ed, maybe not base url but folder should be added only, maybe GET command also should be included, maybe all of it shall be upper cased, maybe lower cased! all with and without "?"
maybe I put only tonce for MD5 and access_id with secret_key in header, and this list goes on with more probabilities.

I sent "*some*" request to them for help, no success, so I am asking help here too.
My ((Sample)) code:

	AnsiString BaseURL="https://api.coinex.com/v1/";
	AnsiString Folder ="balance/info";
	AnsiString QueMark="?";
	AnsiString MyStr="access_id=123&tonce=1590000000000&secret_key=12345"
	AnsiString AuthorizationCode=Md5(
		//QueMark+ //that I try both ways
		MyStr);
	RESTClient1->Params->AddHeader("authorization", AuthorizationCode);
	RESTClient1->Params->AddHeader("User-Agent","Mozilla/...as what they said...");
	RESTClient1->Accept="application/json";
	RESTClient1->AcceptCharset="UTF-8";
	RESTClient1->AcceptEncoding="*";
	RESTClient1->ContentType="application/x-www-form-urlencoded"
	RESTClient1->AllowCookies=true;//false??
	RESTClient1->AutoCreateParams=true;//false??

	RESTClient1->BaseURL=BaseURL+Folder+QueMark+MyStr;
	RESTRequest1->Execute();
	MemoResult->Lines->Text=RESTResponse1->Content;

**Comment by JKorf** [comment]
Have a look at the CoinExAuthenticationProvider class, it handles the authentication for this library
