### ISSUE TITLE
Strange behaviour of CoinExSymbolOrderBook

### ISSUE THREAD

**Issue by mms-x** [JKorf/CoinEx.Net#17]
Firstly, thanks for such a great library!

I noticed that after some period of time, SymolOrderBook stop distributing data, at least it sends empty order book and after that - silence. Status is "Synced". Have check Coinex, but exchange sends data correctly, without outages.

Same problem with Kucoin symbol orderbook.

Thats short example 
```
var orderbook = new CoinExSymbolOrderBook(symbol, new CoinExOrderBookOptions()); 
await orderBook.StartAsync().ConfigureAwait(false);
....
 var updateNumber = instance.OrderBook.LastSequenceNumber;
while (!Token.IsCancellationRequested)
            {
                    if (updateNumber != OrderBook.LastSequenceNumber)
                    {
                        OnOrderBook(orderBook); //Event
                        updateNumber = instance.OrderBook.LastSequenceNumber;
                    }
                    Thread.Sleep(100);
            }
```

**Comment by JKorf** [comment]
Hi, do you have any indication after how long it stops? I've had your sample code running for a couple of hours but it's still updating.
