### ISSUE TITLE
Error invalid parameter in SubscribeToOrderUpdates

### ISSUE THREAD

**Issue by fotrosi** [JKorf/CoinEx.Net#25]
Hi,
I have the following error when using the SubscribeToOrderUpdates method:
Error:invalid argument code:1
This is my code:
var symbols = new List<string>();
symbols.Add("BTCUSDT");
var sub06 = ws.SubscribeToOrderUpdates(symbols, (updateType, data) => { });
if (!sub06.Success)
{
 Console.WriteLine($"SubscribeToOrderUpdates Error:{sub06.Error.Message} code:{sub06.Error.Code}");
}
Thx.

**Comment by JKorf** [comment]
Thanks for the reports, this has been fixed in 3.24.
