### ISSUE TITLE
Warning for trade update

### ISSUE THREAD

**Issue by EricGarnier** [JKorf/CoinEx.Net#32]
When I subscribe to the trade information, I received this warning:

"[2021/05/01 12:27:54.368, (36, .)] INFO: 2021/05/01 12:27:54:368 | CoinEx     | Warning | Received unexpected data format for trade update. Expected 2 objects, received 3. Data: [ONESUSDT,[\r\n  {\r\n    \"id\": 2275032287,\r\n    \"order_id\": 45397170793,\r\n    \"client_id\": \"\",\r\n    \"time\": 1619872074.354161,\r\n    \"type\": \"sell\",\r\n    \"amount\": \"12.72533333\",\r\n    \"price\": \"1.0500\"\r\n  }\r\n],True]",

"[2021/05/01 12:27:54.974, (36, .)] INFO: 2021/05/01 12:27:54:974 | CoinEx     | Warning | Received unexpected data format for trade update. Expected 2 objects, received 3. Data: [ONESUSDT,[\r\n  {\r\n    \"id\": 2275032292,\r\n    \"order_id\": 45397170793,\r\n    \"client_id\": \"\",\r\n    \"time\": 1619872074.629507,\r\n    \"type\": \"sell\",\r\n    \"amount\": \"8.55734985\",\r\n    \"price\": \"1.0500\"\r\n  }\r\n],True]",

Someone add a True a the end?

Eric

**Comment by JKorf** [comment]
Hm weird, I don't get it while testing just now, but it wouldn't be the first time CoinEx has added some random parameter, So the extra parameter is just ignored in the latest version now.
