### ISSUE TITLE
GetDepositHistoryHistoryAsync Fails to decode du to has_next field (at least).

### ISSUE THREAD

**Issue by EricGarnier** [JKorf/CoinEx.Net#33]
Hi @JKorf ,
I got an error during call to GetDepositHistoryHistoryAsync. It seems that the "has_next" field was not expected.
Maybe we must use a `CoinExPagedResult<IEnumerable<CoinExDeposit>>`  or something similar?
The debug trace is below.

Eric

2021/05/23 11:41:10:952 | CoinEx     | Debug | Client configuration: LogVerbosity: Debug, Writers: 2, Credentials: Set, BaseAddress: https://api.coinex.com/v1/, Proxy: -, RateLimiters: 0, RateLimitBehaviour: Wait, RequestTimeout: 00:00:30
2021/05/23 11:41:14:318 | CoinEx     | Debug | [1] Creating request for https://api.coinex.com/v1/balance/coin/deposit
2021/05/23 11:41:14:333 | CoinEx     | Debug | [1] Sending GET signed request to https://api.coinex.com/v1/balance/coin/deposit?access_id=5ZZZZZZZZZZZZZZZZZZZZZZZZZZZ&coin_type=ZEN&tonce=1621762874319
2021/05/23 11:41:14:813 | CoinEx     | Debug | [1] Response received in 476ms: {"code": 0, "data": {"has_next": false, "curr_page": 1, "count": 1, "data": [{"coin_deposit_id": 6177984, "create_time": 1621630590, "amount": "4.1", "amount_display": "4.1", "actual_amount": "4.1", "actual_amount_display": "4.1", "confirmations": 20, "tx_id": "d09b829819f5bcd0de442b86f8381a52b4bd46a607c61729bae1e4e94d540b90", "tx_id_display": "d09b829819f5bcd0de442b86f8381a52b4bd46a607c61729bae1e4e94d540b90", "coin_address": "znYvvoaB383eCgAR8Fxpe6z9dXW8WBemvmr", "coin_address_display": "znYvvo****Bemvmr", "add_explorer": "https://explorer.zensystem.io/address/znYvvoaB383eCgAR8Fxpe6z9dXW8WBemvmr", "coin_type": "ZEN", "smart_contract_name": "", "transfer_method": "onchain", "status": "finish", "status_display": "finish", "remark": "", "explorer": "https://explorer.zensystem.io/tx/d09b829819f5bcd0de442b86f8381a52b4bd46a607c61729bae1e4e94d540b90"}], "total": 1, "total_page": 1}, "message": "Success"}
2021/05/23 11:41:14:831 | CoinEx     | Error | [1] Deserialize JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.IEnumerable`1[CoinEx.Net.Objects.CoinExDeposit]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'data.has_next', line 1, position 32.

**Comment by EricGarnier** [comment]
Work fine with
`CoinExPagedResult<CoinExDeposit>`
And 
 `return await ExecutePaged<CoinExDeposit>(GetUrl(DepositHistoryEndpoint), HttpMethod.Get, ct, parameters, true).ConfigureAwait(false);`

Eric

**Comment by JKorf** [comment]
Fix has been merged
