### ISSUE TITLE
SubscribeToOrderUpdatesAsync error

### ISSUE THREAD

**Issue by behnamfarnoushfar** [JKorf/CoinEx.Net#35]
**Describe the bug**
SubscribeToOrderUpdatesAsync returns invalid arguments (Error:1: invalid argument )

**To Reproduce**
var r=await socket.SubscribeToOrderUpdatesAsync(new[] { "DOGEUSDT" }, (updateType, data) =>
                {
                    var actual = data;
                });

**Expected behavior**
r.success must be true

**Comment by JKorf** [comment]
This has been fixed in the latest beta
