### ISSUE TITLE
How to Create Perpetual Order 

### ISSUE THREAD

**Issue by hadaeghimohsen** [JKorf/CoinEx.Net#36]
Hi guys,
I want to see how to create 'PERPETUAL ORDER' with API.
Thanks for help me.

**Comment by hyperms** [comment]
Seems this API does not exist.

**Comment by hadaeghimohsen** [comment]
It is not possible to add this option to the API.

**Comment by hadaeghimohsen** [comment]
I want to see How to create spot - limited order with API.
Thanks

**Comment by JKorf** [comment]
Although it will probably be implemented eventually it does not have my priority and I can't give a time estimate on it. I'll leave #42 open for this if there is any update
