### ISSUE TITLE
Misspelled MAKER_ONLY in CoinEx.Net/CoinEx.Net/Converters/OrderOptionConverter.cs

### ISSUE THREAD

**Issue by EricGarnier** [JKorf/CoinEx.Net#46]
Hi JKorf,
I notice a typo error:
Line 17 is 
     new KeyValuePair<OrderOption, string>(OrderOption.MakerOnly, "MAKE**N**_ONLY")

Should be 
     new KeyValuePair<OrderOption, string>(OrderOption.MakerOnly, "MAKE**R**_ONLY")

Eric

**Comment by JKorf** [comment]
Fixed
