### ISSUE TITLE
Please, add Asset and Chain properties to CoinExAssetConfig class

### ISSUE THREAD

**Issue by andreafi** [JKorf/CoinEx.Net#47]
The CoinExAssetConfig class miss the asset and chain properties useful for deposit and withdraw.
I suggest you to add:

        /// <summary>
        /// Asset code
        /// </summary>
        [JsonProperty("asset")]
        public string Asset { get; set; }

        /// <summary>
        /// Withdraw & Deposit asset chain
        /// </summary>
        [JsonProperty("chain")]
        public string Chain { get; set; }

Thanks a lot.

Andrea

**Comment by JKorf** [comment]
Fixed
