### ISSUE TITLE
it seems that GetBalancesAsync and GetUserTradesAsync functions are not working

### ISSUE THREAD

**Issue by Kafshdouzi** [JKorf/CoinEx.Net#48]
Hi,
first of all, I am a newbie here :) I managed to communicate with the coinex but in the last 2 or 3 days, GetBalancesAsync and GetUserTradesAsync functions were not working. all the codes which worked well in the last months are now out of work,
please check the issue
BR,

**Comment by Kafshdouzi** [comment]
Also, the Error "227:TimeStamp check Error" is returned when checking for balance by GetBalancesAsync

**Comment by EricGarnier** [comment]
This is a known issue. @JKorf  has already made a correction, but it is not yet in the release.
In the mean time, you can just create a class CoinExNonceProvider  with the same code than the last commit, and put in in your CoinExOption in the NonceProvider field.

Something like

`	
class CoinExNonceProvider : INonceProvider
    {
        private static DateTime unix = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);
        private static readonly object nonceLock = new object();
        private static long? lastNonce;

        /// <inheritdoc />
        public long GetNonce()
        {
            lock (nonceLock)
            {
                var nonce = (long)Math.Round((DateTime.UtcNow - unix).TotalMilliseconds);
                if (lastNonce.HasValue && nonce <= lastNonce.Value)
                    nonce = lastNonce.Value + 1;
                lastNonce = nonce;
                return nonce;
            }
        }
    }
`

And

`			_coinExOption.NonceProvider = new CoinExNonceProvider();
`

**Comment by Kafshdouzi** [comment]
Thank you @EricGarnier 
as i allready mentioned I am a newbie in programing and unfortunately I could not figure out what you want to say.
i share my siple code here which i briefed it to fine the error ( it is not the whole code but for diagnosing the problem),
the result of this code is "Error 227: Time Stamp check error" now, and i am eager to know, how i would use your mentioned code with this one to acquire the requested data correctly. 
i created "class CoinExNonceProvider : INonceProvider" but to be honest i dont know how to use it and get correct data whitin api.
it would be really helpful if you advise me :)
here is my simple code:
` private void metroButton8_Click(object sender, EventArgs e)
        {

            var client1 = new CoinExClient();
            client1.SetApiCredentials(API_Key,API_Secret);
            
            
            try
            {
                if (client1.GetBalancesAsync().Result)
                {
                    MessageBox.Show("OK");
                }
                else
                {
                    MessageBox.Show(client1.GetBalancesAsync().Result.Error.ToString());
                }

            }
            catch (Exception exception)
            {
                MessageBox.Show(exception.ToString());
                throw;
            }
        }`

**Comment by EricGarnier** [comment]
Just replace the first two lines with 
`
			var coinExOption = new CoinExClientOptions()
			{
				ApiCredentials = new CryptoExchange.Net.Authentication.ApiCredentials(API_Key,API_Secret),
			};
			coinExOption.NonceProvider = new CoinExNonceProvider();
                        var client1 = new CoinExClient(coinExOption);

`

**Comment by Kafshdouzi** [comment]
Dear @EricGarnier 
Thanks a lot :), it's really helpful, your provided solution works fine and the problem is solved.
thank you again
