### ISSUE TITLE
withdraw error + format symbol

### ISSUE THREAD

**Issue by mehdijalili2000** [JKorf/CoinEx.Net#53]
Hi. 
I want withdraw with coinex nuget and I have some questions 
1- Symbol format (syntax) in withdraw command. e.g : "DOGE-USDT" or "DOGE/USDT" or ...
2- in withdraw i getting error ; 
   var TransferfromCoinexRes = await clientCoinex.WithdrawAsync("DOGE/USDT", addr,true,1);
{25: Signature Incorrect }

3-In parameters of withdraw,There is no parameter based on the type of network.
4- withdraw in coinex site It asks me for the topt password, but here's what we need to do.
 Explain that I whitelisted the address 
good luck thank you

**Comment by mehdijalili2000** [comment]
Please write the steps and parameters required for a currency like "dogeusdt"

**Comment by JKorf** [comment]
I'll add a `network` parameter in the latest alpha version. What you're trying to do doesn't make any sense though. Are you trying to withdraw `usdt` or `doge`? You can't withdraw `dogeusdt` as it is a trade market, not an asset.

**Comment by mehdijalili2000** [comment]
Hi tank you. i want to withdraw usdt or doge or ... 
but recive error and Formats vary in different coin
I used most of your programs in different exchanges, but they do not have a user guide because the formats are different and most of them give errors.
