### ISSUE TITLE
Coinex Futures request

### ISSUE THREAD

**Issue by emrah1455** [JKorf/CoinEx.Net#57]
Hi Jan Korf, first of all I thank you for your labor, I am grateful for your efforts.I think it's time to add the futures feature.May I ask you to add futures to your package? I would like to give you a Cet token gift, because coinex is improving itself, and now there are tradingview charts on coinex. I don't know december you know, by the way, Coinex created the Coinex Smart Chain network .
by the way, I apologize for my bad English.

**Comment by danielhw2** [comment]
I also like to see futures implemented... 🙏

**Comment by vatttanweb** [comment]
May I know the date of release of future API?

**Comment by ErdincKaragoz** [comment]
Hi Jan, 

I agree, it would be very nice if futures API is also supported and if you guide us via documentation on how to (I am new to your cryptoexchange lib) we can also add.

**Comment by JKorf** [comment]
Its taken a little while, but futures is now supported in the latest version
