### ISSUE TITLE
SubscribeToKlineUpdatesAsync return method not found.

### ISSUE THREAD

**Issue by Rayan1392** [JKorf/CoinEx.Net#58]
**SubscribeToKlineUpdatesAsync**
I try to get 5 minutes candles, TwoHour or other candles via _SubscribeToKlineUpdatesAsync_ but I get this response:

listResult.Data
{
   data : null,
   Error: {
     code : 4,
    data : null,
    message: "method not found"
   },
   Success: False
}
please help me to fix this problem.

```
 using(var sockClient = new CoinExSocketClient())
  {
      var listResult = await sockClient.SubscribeToKlineUpdatesAsync("ADAUSDT", Objects.KlineInterval.TwoHour, (e )=> {

          Console.WriteLine(e.Data.FirstOrDefault().Close);
          
      
      });
      Console.WriteLine(listResult);


  }
```

**Comment by JKorf** [comment]
This is an issue on the CoinEx server for as long as I remember. I (and other users as well) have reported this on their Github repo but never got any response.
