### ISSUE TITLE
Not all CoinEx APIs are implemented

### ISSUE THREAD

**Issue by hatami57** [JKorf/CoinEx.Net#61]
Hi,

Thank you for your great libraries.

As CoinEx support team stated [here](https://support.coinex.com/hc/en-us/articles/900004316323-What-is-API-and-How-to-Set-it-Up-) the API documentation and specs are located at [https://viabtc.github.io/coinex_api_en_doc/](https://viabtc.github.io/coinex_api_en_doc/).
I figure it out that not all APIs are implemented yet, maybe it's because you are using an older version of document.

for example, there is an API for cancelling a stop order in CoinEx ([here](https://viabtc.github.io/coinex_api_en_doc/spot/#docsspot003_trade018_cancle_stop_pending_order)) which is not exists in the library.

**Comment by JKorf** [comment]
I've updated the library for the V2 API, everything should be there in the latest version
