### ISSUE TITLE
Signature issue for char not letter nor digit

### ISSUE THREAD

**Issue by EricGarnier** [JKorf/CoinEx.Net#62]
Hi JKorf,
first, thanks for all this super work.

I notice a small issue when I try to withdraw from coinex. I got a signature error message. This seems to be du to the presence of a : char in the destination address.

According to the CoinEx signature sample here [(class CoinExClient),](https://github.com/coinexcom/coinex_exchange_api/blob/master/csharp/CoinEx.cs), line 27, the signature should be calculated over a big string containing the parameters. Their is no escape of the parameter values. 

` var body = string.Join("&", sortedArgs.Select(p => $"{p.Key}={p.Value}"));`
` //calc md5`
` var md5 = MD5.Create().ComputeHash(Encoding.UTF8.GetBytes(body));`

But in your code, you use an Http Utility NameValueCollection, in ExtensionMethods.cs 
`            NameValueCollection nameValueCollection = HttpUtility.ParseQueryString(string.Empty);`
...
`            uriBuilder.Query = nameValueCollection.ToString();
`

This code replace the : char by %3a
This make the signature to be wrong.

I think you can reproduce with any method that accept a not letter or digit parameter value. 
HTH,
Eric

**Comment by JKorf** [comment]
Hi, thanks for the report. I've fixed the issue in the latest version
