### ISSUE TITLE
Error : Code:4004 invalid argument while placing MARKET order

### ISSUE THREAD

**Issue by H-Moradof** [JKorf/CoinEx.Net#80]
**Describe the bug**
I try to put a SELL order on MARKET .

here is my code:
`var result = await _client.SpotApiV2.Trading.PlaceOrderAsync("TRXUSDT", AccountType.Spot, OrderSide.Sell, OrderTypeV2.Market, quantity: 30.00000000, clientOrderId: "72e74f88-1727-4098-822e-25ccc5705f08");`

and here is the request detail sending to coinex api:
request url:
"https://api.coinex.com/v2/spot/order"

request body : 
{
"amount":"30.00000000",
"client_id":"72e74f88-1727-4098-822e-25ccc5705f08",
"market":"TRXUSDT",
"market_type":"SPOT",
"side":"sell",
"type":"market"
}

response I have got from coinex api is :
{
"Error": {
"Code":4004,
"Message":"invalid argument",
"Data":null
}, 
"Success":false
}

I ALSO try this:

`var result = await _client.SpotApiV2.Trading.PlaceOrderAsync("TRXUSDT", AccountType.Spot, OrderSide.Sell, OrderTypeV2.Market, quantity: 30.00000000, clientOrderId: "72e74f88-1727-4098-822e-25ccc5705f08",quantityAsset:"TRX");`
but I got same ERROR.

**Am I doing something wrong ?**

**Comment by H-Moradof** [comment]
here is the Coinex Support comment:

We can't see the authorization part. The code examples for spot/order were correct.
You can verify that you've written the correct request header for your code. Make sure you've included Content-Type.

**Comment by JKorf** [comment]
Hi, CoinEx support is incorrect. The problem is your clientOrderId parameter. It has a length of 36 characters, while the field has a max of 32 characters.
