### ISSUE TITLE
set ApiCredentials from db

### ISSUE THREAD

**Issue by H-Moradof** [JKorf/CoinEx.Net#81]
Hi, 
my api key and secret key is in database (it's encrypted).
I tried to read database and set ApiCredentials in Configure() method, but it does Not work.

`public void ConfigureServices(IServiceCollection services)
{
    
    // Register CoinEx  without credentials for now
    services.AddCoinEx(restOptions =>
    {
        restOptions.RequestTimeout = TimeSpan.FromSeconds(5);
    },
    socketOptions =>
    {
        // Leaving empty for now
    });

}`

`public void Configure(IApplicationBuilder app, IWebHostEnvironment env, IServiceProvider serviceProvider)
{

    var appConfigRepository = serviceProvider.GetRequiredService();

    string coinexApiKey = appConfigRepository.GetStringConfig(ApplicationSettingKey.COINEX_API_KEY);
    string coinexSecretKey = appConfigRepository.GetStringConfig(ApplicationSettingKey.COINEX_API_KEY);

    var coinExClient = serviceProvider.GetRequiredService<ICoinExRestClient>();
    coinExClient.SetApiCredentials(new ApiCredentials(coinexApiKey, coinexSecretKey));

    var coinExSocketClient = serviceProvider.GetRequiredService<ICoinExSocketClient>();
    coinExSocketClient.SetApiCredentials(new ApiCredentials(coinexApiKey, coinexSecretKey));

}`

is any way I can fix this ?

**Comment by H-Moradof** [comment]
I got this exception when trying to call api:

Error Message: "No credentials provided for private endpoint"

**Comment by JKorf** [comment]
Hi, what you tried doesn't work as it is only applied to that specific client instance, when you inject a new client later it's a new instance.

You could use SetDefaultOptions in the Configure method to set the ApiCredentials instead:
```csharp
CoinExRestClient.SetDefaultOptions(x =>
{
    x.ApiCredentials = new ApiCredentials("123", "456");
});
```

**Comment by H-Moradof** [comment]
I thought client is singleton, so just one instance is in the whole application.
thanks for helping
